global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: "telegram"

receivers:
  - name: "telegram"
    telegram_configs:
      - bot_token: "8311762477:AAHg9d3QNcioPjMvBZyZcJtnB9YdV10XQTA"
        chat_id: 6207272674
        message: |
          🚨 *{{ .GroupLabels.alertname }}*
          Status: {{ .Status | toUpper }}
          {{ range .Alerts }}
          • {{ .Annotations.summary }}
          {{ end }}
        parse_mode: "Markdown"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "job"]
